-- DYEING AI WEB V1
-- Run this SQL in Supabase SQL Editor.
create table if not exists public.dyeing_cases (
  id bigint generated by default as identity primary key,
  case_id text unique not null,
  product_code text not null,
  batch_no text not null,
  machine text not null,
  event_date date not null,
  problem text not null,
  description text not null,
  photo_urls text[] default '{}',
  status text not null default 'OPEN',
  treatment text,
  result text,
  effective text,
  next_action text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_dyeing_product on public.dyeing_cases(product_code);
create index if not exists idx_dyeing_batch on public.dyeing_cases(batch_no);
create index if not exists idx_dyeing_problem on public.dyeing_cases(problem);
create index if not exists idx_dyeing_date on public.dyeing_cases(event_date);

alter table public.dyeing_cases enable row level security;

-- TEST POLICY ONLY.
-- For the first internal test, allow anonymous browser reads/inserts.
-- Replace these policies with authenticated worker/technician policies before production.
drop policy if exists "demo read" on public.dyeing_cases;
drop policy if exists "demo insert" on public.dyeing_cases;
create policy "demo read" on public.dyeing_cases for select using (true);
create policy "demo insert" on public.dyeing_cases for insert with check (true);
